changelog-seen = 2

[build]
target = [
	"riscv32im-succinct-zkvm-elf",
	"riscv64im-unicorn-zkvm-elf",
	"riscv64gc-unicorn-zkvm-elf",
]
extended = true
tools = ["cargo", "cargo-clippy", "clippy", "rustfmt"]
configure-args = []

[rust]
lld = true
llvm-tools = true
channel = "nightly"

[llvm]
download-ci-llvm = false
